------------------------------------------------------------------------------
-- |
-- Module:      Database.PostgreSQL.Simple.TypeInfo
-- Copyright:   (c) 2011-2012 Leon P Smith
-- License:     BSD3
-- Maintainer:  Leon P Smith <leon@melding-monads.com>
-- Stability:   experimental
--
-- This module contains portions of the @pg_type@ table that are relevant
-- to postgresql-simple and are believed to not change between PostgreSQL
-- versions.
--
------------------------------------------------------------------------------

-- Note that this file is generated by tools/GenTypeInfo.hs, and should
-- not be edited directly

module Database.PostgreSQL.Simple.TypeInfo.Static
     ( TypeInfo(..)
     , staticTypeInfo
     , bool
     , bytea
     , char
     , name
     , int8
     , int2
     , int2vector
     , int4
     , regproc
     , text
     , oid
     , tid
     , xid
     , cid
     , oidvector
     , pg_ddl_command
     , pg_type
     , pg_attribute
     , pg_proc
     , pg_class
     , json
     , xml
     , pg_node_tree
     , smgr
     , index_am_handler
     , point
     , lseg
     , path
     , box
     , polygon
     , line
     , cidr
     , float4
     , float8
     , abstime
     , reltime
     , tinterval
     , unknown
     , circle
     , macaddr8
     , money
     , macaddr
     , inet
     , aclitem
     , bpchar
     , varchar
     , date
     , time
     , timestamp
     , timestamptz
     , interval
     , pg_database
     , timetz
     , bit
     , varbit
     , numeric
     , refcursor
     , regprocedure
     , regoper
     , regoperator
     , regclass
     , regtype
     , record
     , cstring
     , any
     , anyarray
     , void
     , trigger
     , language_handler
     , internal
     , opaque
     , anyelement
     , anynonarray
     , pg_authid
     , pg_auth_members
     , uuid
     , txid_snapshot
     , fdw_handler
     , pg_lsn
     , tsm_handler
     , pg_ndistinct
     , pg_dependencies
     , anyenum
     , tsvector
     , tsquery
     , gtsvector
     , regconfig
     , regdictionary
     , jsonb
     , anyrange
     , event_trigger
     , int4range
     , numrange
     , tsrange
     , tstzrange
     , daterange
     , int8range
     , pg_shseclabel
     , regnamespace
     , regrole
     , array_xml
     , array_json
     , array_line
     , array_cidr
     , array_circle
     , array_macaddr8
     , array_money
     , array_bool
     , array_bytea
     , array_char
     , array_name
     , array_int2
     , array_int2vector
     , array_int4
     , array_regproc
     , array_text
     , array_tid
     , array_xid
     , array_cid
     , array_oidvector
     , array_bpchar
     , array_varchar
     , array_int8
     , array_point
     , array_lseg
     , array_path
     , array_box
     , array_float4
     , array_float8
     , array_abstime
     , array_reltime
     , array_tinterval
     , array_polygon
     , array_oid
     , array_aclitem
     , array_macaddr
     , array_inet
     , array_timestamp
     , array_date
     , array_time
     , array_timestamptz
     , array_interval
     , array_numeric
     , array_cstring
     , array_timetz
     , array_bit
     , array_varbit
     , array_refcursor
     , array_regprocedure
     , array_regoper
     , array_regoperator
     , array_regclass
     , array_regtype
     , array_record
     , array_txid_snapshot
     , array_uuid
     , array_pg_lsn
     , array_tsvector
     , array_gtsvector
     , array_tsquery
     , array_regconfig
     , array_regdictionary
     , array_jsonb
     , array_int4range
     , array_numrange
     , array_tsrange
     , array_tstzrange
     , array_daterange
     , array_int8range
     , array_regnamespace
     , array_regrole
     ) where

import Database.PostgreSQL.LibPQ (Oid(..))
import Database.PostgreSQL.Simple.TypeInfo.Types
import Prelude hiding (any)

staticTypeInfo :: Oid -> Maybe TypeInfo
staticTypeInfo (Oid x) = case x of
    16   -> Just bool
    17   -> Just bytea
    18   -> Just char
    19   -> Just name
    20   -> Just int8
    21   -> Just int2
    22   -> Just int2vector
    23   -> Just int4
    24   -> Just regproc
    25   -> Just text
    26   -> Just oid
    27   -> Just tid
    28   -> Just xid
    29   -> Just cid
    30   -> Just oidvector
    32   -> Just pg_ddl_command
    71   -> Just pg_type
    75   -> Just pg_attribute
    81   -> Just pg_proc
    83   -> Just pg_class
    114  -> Just json
    142  -> Just xml
    194  -> Just pg_node_tree
    210  -> Just smgr
    325  -> Just index_am_handler
    600  -> Just point
    601  -> Just lseg
    602  -> Just path
    603  -> Just box
    604  -> Just polygon
    628  -> Just line
    650  -> Just cidr
    700  -> Just float4
    701  -> Just float8
    702  -> Just abstime
    703  -> Just reltime
    704  -> Just tinterval
    705  -> Just unknown
    718  -> Just circle
    774  -> Just macaddr8
    790  -> Just money
    829  -> Just macaddr
    869  -> Just inet
    1033 -> Just aclitem
    1042 -> Just bpchar
    1043 -> Just varchar
    1082 -> Just date
    1083 -> Just time
    1114 -> Just timestamp
    1184 -> Just timestamptz
    1186 -> Just interval
    1248 -> Just pg_database
    1266 -> Just timetz
    1560 -> Just bit
    1562 -> Just varbit
    1700 -> Just numeric
    1790 -> Just refcursor
    2202 -> Just regprocedure
    2203 -> Just regoper
    2204 -> Just regoperator
    2205 -> Just regclass
    2206 -> Just regtype
    2249 -> Just record
    2275 -> Just cstring
    2276 -> Just any
    2277 -> Just anyarray
    2278 -> Just void
    2279 -> Just trigger
    2280 -> Just language_handler
    2281 -> Just internal
    2282 -> Just opaque
    2283 -> Just anyelement
    2776 -> Just anynonarray
    2842 -> Just pg_authid
    2843 -> Just pg_auth_members
    2950 -> Just uuid
    2970 -> Just txid_snapshot
    3115 -> Just fdw_handler
    3220 -> Just pg_lsn
    3310 -> Just tsm_handler
    3361 -> Just pg_ndistinct
    3402 -> Just pg_dependencies
    3500 -> Just anyenum
    3614 -> Just tsvector
    3615 -> Just tsquery
    3642 -> Just gtsvector
    3734 -> Just regconfig
    3769 -> Just regdictionary
    3802 -> Just jsonb
    3831 -> Just anyrange
    3838 -> Just event_trigger
    3904 -> Just int4range
    3906 -> Just numrange
    3908 -> Just tsrange
    3910 -> Just tstzrange
    3912 -> Just daterange
    3926 -> Just int8range
    4066 -> Just pg_shseclabel
    4089 -> Just regnamespace
    4096 -> Just regrole
    143  -> Just array_xml
    199  -> Just array_json
    629  -> Just array_line
    651  -> Just array_cidr
    719  -> Just array_circle
    775  -> Just array_macaddr8
    791  -> Just array_money
    1000 -> Just array_bool
    1001 -> Just array_bytea
    1002 -> Just array_char
    1003 -> Just array_name
    1005 -> Just array_int2
    1006 -> Just array_int2vector
    1007 -> Just array_int4
    1008 -> Just array_regproc
    1009 -> Just array_text
    1010 -> Just array_tid
    1011 -> Just array_xid
    1012 -> Just array_cid
    1013 -> Just array_oidvector
    1014 -> Just array_bpchar
    1015 -> Just array_varchar
    1016 -> Just array_int8
    1017 -> Just array_point
    1018 -> Just array_lseg
    1019 -> Just array_path
    1020 -> Just array_box
    1021 -> Just array_float4
    1022 -> Just array_float8
    1023 -> Just array_abstime
    1024 -> Just array_reltime
    1025 -> Just array_tinterval
    1027 -> Just array_polygon
    1028 -> Just array_oid
    1034 -> Just array_aclitem
    1040 -> Just array_macaddr
    1041 -> Just array_inet
    1115 -> Just array_timestamp
    1182 -> Just array_date
    1183 -> Just array_time
    1185 -> Just array_timestamptz
    1187 -> Just array_interval
    1231 -> Just array_numeric
    1263 -> Just array_cstring
    1270 -> Just array_timetz
    1561 -> Just array_bit
    1563 -> Just array_varbit
    2201 -> Just array_refcursor
    2207 -> Just array_regprocedure
    2208 -> Just array_regoper
    2209 -> Just array_regoperator
    2210 -> Just array_regclass
    2211 -> Just array_regtype
    2287 -> Just array_record
    2949 -> Just array_txid_snapshot
    2951 -> Just array_uuid
    3221 -> Just array_pg_lsn
    3643 -> Just array_tsvector
    3644 -> Just array_gtsvector
    3645 -> Just array_tsquery
    3735 -> Just array_regconfig
    3770 -> Just array_regdictionary
    3807 -> Just array_jsonb
    3905 -> Just array_int4range
    3907 -> Just array_numrange
    3909 -> Just array_tsrange
    3911 -> Just array_tstzrange
    3913 -> Just array_daterange
    3927 -> Just array_int8range
    4090 -> Just array_regnamespace
    4097 -> Just array_regrole
    _ -> Nothing

bool :: TypeInfo
bool =  Basic {
    typoid      = Oid 16,
    typcategory = 'B',
    typdelim    = ',',
    typname     = "bool"
  }

bytea :: TypeInfo
bytea =  Basic {
    typoid      = Oid 17,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "bytea"
  }

char :: TypeInfo
char =  Basic {
    typoid      = Oid 18,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "char"
  }

name :: TypeInfo
name =  Basic {
    typoid      = Oid 19,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "name"
  }

int8 :: TypeInfo
int8 =  Basic {
    typoid      = Oid 20,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "int8"
  }

int2 :: TypeInfo
int2 =  Basic {
    typoid      = Oid 21,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "int2"
  }

int2vector :: TypeInfo
int2vector =  Array {
    typoid      = Oid 22,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "int2vector",
    typelem     = int2
  }

int4 :: TypeInfo
int4 =  Basic {
    typoid      = Oid 23,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "int4"
  }

regproc :: TypeInfo
regproc =  Basic {
    typoid      = Oid 24,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regproc"
  }

text :: TypeInfo
text =  Basic {
    typoid      = Oid 25,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "text"
  }

oid :: TypeInfo
oid =  Basic {
    typoid      = Oid 26,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "oid"
  }

tid :: TypeInfo
tid =  Basic {
    typoid      = Oid 27,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "tid"
  }

xid :: TypeInfo
xid =  Basic {
    typoid      = Oid 28,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "xid"
  }

cid :: TypeInfo
cid =  Basic {
    typoid      = Oid 29,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "cid"
  }

oidvector :: TypeInfo
oidvector =  Array {
    typoid      = Oid 30,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "oidvector",
    typelem     = oid
  }

pg_ddl_command :: TypeInfo
pg_ddl_command =  Basic {
    typoid      = Oid 32,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "pg_ddl_command"
  }

pg_type :: TypeInfo
pg_type =  Basic {
    typoid      = Oid 71,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_type"
  }

pg_attribute :: TypeInfo
pg_attribute =  Basic {
    typoid      = Oid 75,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_attribute"
  }

pg_proc :: TypeInfo
pg_proc =  Basic {
    typoid      = Oid 81,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_proc"
  }

pg_class :: TypeInfo
pg_class =  Basic {
    typoid      = Oid 83,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_class"
  }

json :: TypeInfo
json =  Basic {
    typoid      = Oid 114,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "json"
  }

xml :: TypeInfo
xml =  Basic {
    typoid      = Oid 142,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "xml"
  }

pg_node_tree :: TypeInfo
pg_node_tree =  Basic {
    typoid      = Oid 194,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "pg_node_tree"
  }

smgr :: TypeInfo
smgr =  Basic {
    typoid      = Oid 210,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "smgr"
  }

index_am_handler :: TypeInfo
index_am_handler =  Basic {
    typoid      = Oid 325,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "index_am_handler"
  }

point :: TypeInfo
point =  Basic {
    typoid      = Oid 600,
    typcategory = 'G',
    typdelim    = ',',
    typname     = "point"
  }

lseg :: TypeInfo
lseg =  Basic {
    typoid      = Oid 601,
    typcategory = 'G',
    typdelim    = ',',
    typname     = "lseg"
  }

path :: TypeInfo
path =  Basic {
    typoid      = Oid 602,
    typcategory = 'G',
    typdelim    = ',',
    typname     = "path"
  }

box :: TypeInfo
box =  Basic {
    typoid      = Oid 603,
    typcategory = 'G',
    typdelim    = ';',
    typname     = "box"
  }

polygon :: TypeInfo
polygon =  Basic {
    typoid      = Oid 604,
    typcategory = 'G',
    typdelim    = ',',
    typname     = "polygon"
  }

line :: TypeInfo
line =  Basic {
    typoid      = Oid 628,
    typcategory = 'G',
    typdelim    = ',',
    typname     = "line"
  }

cidr :: TypeInfo
cidr =  Basic {
    typoid      = Oid 650,
    typcategory = 'I',
    typdelim    = ',',
    typname     = "cidr"
  }

float4 :: TypeInfo
float4 =  Basic {
    typoid      = Oid 700,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "float4"
  }

float8 :: TypeInfo
float8 =  Basic {
    typoid      = Oid 701,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "float8"
  }

abstime :: TypeInfo
abstime =  Basic {
    typoid      = Oid 702,
    typcategory = 'D',
    typdelim    = ',',
    typname     = "abstime"
  }

reltime :: TypeInfo
reltime =  Basic {
    typoid      = Oid 703,
    typcategory = 'T',
    typdelim    = ',',
    typname     = "reltime"
  }

tinterval :: TypeInfo
tinterval =  Basic {
    typoid      = Oid 704,
    typcategory = 'T',
    typdelim    = ',',
    typname     = "tinterval"
  }

unknown :: TypeInfo
unknown =  Basic {
    typoid      = Oid 705,
    typcategory = 'X',
    typdelim    = ',',
    typname     = "unknown"
  }

circle :: TypeInfo
circle =  Basic {
    typoid      = Oid 718,
    typcategory = 'G',
    typdelim    = ',',
    typname     = "circle"
  }

macaddr8 :: TypeInfo
macaddr8 =  Basic {
    typoid      = Oid 774,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "macaddr8"
  }

money :: TypeInfo
money =  Basic {
    typoid      = Oid 790,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "money"
  }

macaddr :: TypeInfo
macaddr =  Basic {
    typoid      = Oid 829,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "macaddr"
  }

inet :: TypeInfo
inet =  Basic {
    typoid      = Oid 869,
    typcategory = 'I',
    typdelim    = ',',
    typname     = "inet"
  }

aclitem :: TypeInfo
aclitem =  Basic {
    typoid      = Oid 1033,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "aclitem"
  }

bpchar :: TypeInfo
bpchar =  Basic {
    typoid      = Oid 1042,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "bpchar"
  }

varchar :: TypeInfo
varchar =  Basic {
    typoid      = Oid 1043,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "varchar"
  }

date :: TypeInfo
date =  Basic {
    typoid      = Oid 1082,
    typcategory = 'D',
    typdelim    = ',',
    typname     = "date"
  }

time :: TypeInfo
time =  Basic {
    typoid      = Oid 1083,
    typcategory = 'D',
    typdelim    = ',',
    typname     = "time"
  }

timestamp :: TypeInfo
timestamp =  Basic {
    typoid      = Oid 1114,
    typcategory = 'D',
    typdelim    = ',',
    typname     = "timestamp"
  }

timestamptz :: TypeInfo
timestamptz =  Basic {
    typoid      = Oid 1184,
    typcategory = 'D',
    typdelim    = ',',
    typname     = "timestamptz"
  }

interval :: TypeInfo
interval =  Basic {
    typoid      = Oid 1186,
    typcategory = 'T',
    typdelim    = ',',
    typname     = "interval"
  }

pg_database :: TypeInfo
pg_database =  Basic {
    typoid      = Oid 1248,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_database"
  }

timetz :: TypeInfo
timetz =  Basic {
    typoid      = Oid 1266,
    typcategory = 'D',
    typdelim    = ',',
    typname     = "timetz"
  }

bit :: TypeInfo
bit =  Basic {
    typoid      = Oid 1560,
    typcategory = 'V',
    typdelim    = ',',
    typname     = "bit"
  }

varbit :: TypeInfo
varbit =  Basic {
    typoid      = Oid 1562,
    typcategory = 'V',
    typdelim    = ',',
    typname     = "varbit"
  }

numeric :: TypeInfo
numeric =  Basic {
    typoid      = Oid 1700,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "numeric"
  }

refcursor :: TypeInfo
refcursor =  Basic {
    typoid      = Oid 1790,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "refcursor"
  }

regprocedure :: TypeInfo
regprocedure =  Basic {
    typoid      = Oid 2202,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regprocedure"
  }

regoper :: TypeInfo
regoper =  Basic {
    typoid      = Oid 2203,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regoper"
  }

regoperator :: TypeInfo
regoperator =  Basic {
    typoid      = Oid 2204,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regoperator"
  }

regclass :: TypeInfo
regclass =  Basic {
    typoid      = Oid 2205,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regclass"
  }

regtype :: TypeInfo
regtype =  Basic {
    typoid      = Oid 2206,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regtype"
  }

record :: TypeInfo
record =  Basic {
    typoid      = Oid 2249,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "record"
  }

cstring :: TypeInfo
cstring =  Basic {
    typoid      = Oid 2275,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "cstring"
  }

any :: TypeInfo
any =  Basic {
    typoid      = Oid 2276,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "any"
  }

anyarray :: TypeInfo
anyarray =  Basic {
    typoid      = Oid 2277,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "anyarray"
  }

void :: TypeInfo
void =  Basic {
    typoid      = Oid 2278,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "void"
  }

trigger :: TypeInfo
trigger =  Basic {
    typoid      = Oid 2279,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "trigger"
  }

language_handler :: TypeInfo
language_handler =  Basic {
    typoid      = Oid 2280,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "language_handler"
  }

internal :: TypeInfo
internal =  Basic {
    typoid      = Oid 2281,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "internal"
  }

opaque :: TypeInfo
opaque =  Basic {
    typoid      = Oid 2282,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "opaque"
  }

anyelement :: TypeInfo
anyelement =  Basic {
    typoid      = Oid 2283,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "anyelement"
  }

anynonarray :: TypeInfo
anynonarray =  Basic {
    typoid      = Oid 2776,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "anynonarray"
  }

pg_authid :: TypeInfo
pg_authid =  Basic {
    typoid      = Oid 2842,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_authid"
  }

pg_auth_members :: TypeInfo
pg_auth_members =  Basic {
    typoid      = Oid 2843,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_auth_members"
  }

uuid :: TypeInfo
uuid =  Basic {
    typoid      = Oid 2950,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "uuid"
  }

txid_snapshot :: TypeInfo
txid_snapshot =  Basic {
    typoid      = Oid 2970,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "txid_snapshot"
  }

fdw_handler :: TypeInfo
fdw_handler =  Basic {
    typoid      = Oid 3115,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "fdw_handler"
  }

pg_lsn :: TypeInfo
pg_lsn =  Basic {
    typoid      = Oid 3220,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "pg_lsn"
  }

tsm_handler :: TypeInfo
tsm_handler =  Basic {
    typoid      = Oid 3310,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "tsm_handler"
  }

pg_ndistinct :: TypeInfo
pg_ndistinct =  Basic {
    typoid      = Oid 3361,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "pg_ndistinct"
  }

pg_dependencies :: TypeInfo
pg_dependencies =  Basic {
    typoid      = Oid 3402,
    typcategory = 'S',
    typdelim    = ',',
    typname     = "pg_dependencies"
  }

anyenum :: TypeInfo
anyenum =  Basic {
    typoid      = Oid 3500,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "anyenum"
  }

tsvector :: TypeInfo
tsvector =  Basic {
    typoid      = Oid 3614,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "tsvector"
  }

tsquery :: TypeInfo
tsquery =  Basic {
    typoid      = Oid 3615,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "tsquery"
  }

gtsvector :: TypeInfo
gtsvector =  Basic {
    typoid      = Oid 3642,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "gtsvector"
  }

regconfig :: TypeInfo
regconfig =  Basic {
    typoid      = Oid 3734,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regconfig"
  }

regdictionary :: TypeInfo
regdictionary =  Basic {
    typoid      = Oid 3769,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regdictionary"
  }

jsonb :: TypeInfo
jsonb =  Basic {
    typoid      = Oid 3802,
    typcategory = 'U',
    typdelim    = ',',
    typname     = "jsonb"
  }

anyrange :: TypeInfo
anyrange =  Basic {
    typoid      = Oid 3831,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "anyrange"
  }

event_trigger :: TypeInfo
event_trigger =  Basic {
    typoid      = Oid 3838,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "event_trigger"
  }

int4range :: TypeInfo
int4range =  Range {
    typoid      = Oid 3904,
    typcategory = 'R',
    typdelim    = ',',
    typname     = "int4range",
    rngsubtype  = int4
  }

numrange :: TypeInfo
numrange =  Range {
    typoid      = Oid 3906,
    typcategory = 'R',
    typdelim    = ',',
    typname     = "numrange",
    rngsubtype  = numeric
  }

tsrange :: TypeInfo
tsrange =  Range {
    typoid      = Oid 3908,
    typcategory = 'R',
    typdelim    = ',',
    typname     = "tsrange",
    rngsubtype  = timestamp
  }

tstzrange :: TypeInfo
tstzrange =  Range {
    typoid      = Oid 3910,
    typcategory = 'R',
    typdelim    = ',',
    typname     = "tstzrange",
    rngsubtype  = timestamptz
  }

daterange :: TypeInfo
daterange =  Range {
    typoid      = Oid 3912,
    typcategory = 'R',
    typdelim    = ',',
    typname     = "daterange",
    rngsubtype  = date
  }

int8range :: TypeInfo
int8range =  Range {
    typoid      = Oid 3926,
    typcategory = 'R',
    typdelim    = ',',
    typname     = "int8range",
    rngsubtype  = int8
  }

pg_shseclabel :: TypeInfo
pg_shseclabel =  Basic {
    typoid      = Oid 4066,
    typcategory = 'C',
    typdelim    = ',',
    typname     = "pg_shseclabel"
  }

regnamespace :: TypeInfo
regnamespace =  Basic {
    typoid      = Oid 4089,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regnamespace"
  }

regrole :: TypeInfo
regrole =  Basic {
    typoid      = Oid 4096,
    typcategory = 'N',
    typdelim    = ',',
    typname     = "regrole"
  }

array_xml :: TypeInfo
array_xml =  Array {
    typoid      = Oid 143,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_xml",
    typelem     = xml
  }

array_json :: TypeInfo
array_json =  Array {
    typoid      = Oid 199,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_json",
    typelem     = json
  }

array_line :: TypeInfo
array_line =  Array {
    typoid      = Oid 629,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_line",
    typelem     = line
  }

array_cidr :: TypeInfo
array_cidr =  Array {
    typoid      = Oid 651,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_cidr",
    typelem     = cidr
  }

array_circle :: TypeInfo
array_circle =  Array {
    typoid      = Oid 719,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_circle",
    typelem     = circle
  }

array_macaddr8 :: TypeInfo
array_macaddr8 =  Array {
    typoid      = Oid 775,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_macaddr8",
    typelem     = macaddr8
  }

array_money :: TypeInfo
array_money =  Array {
    typoid      = Oid 791,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_money",
    typelem     = money
  }

array_bool :: TypeInfo
array_bool =  Array {
    typoid      = Oid 1000,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_bool",
    typelem     = bool
  }

array_bytea :: TypeInfo
array_bytea =  Array {
    typoid      = Oid 1001,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_bytea",
    typelem     = bytea
  }

array_char :: TypeInfo
array_char =  Array {
    typoid      = Oid 1002,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_char",
    typelem     = char
  }

array_name :: TypeInfo
array_name =  Array {
    typoid      = Oid 1003,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_name",
    typelem     = name
  }

array_int2 :: TypeInfo
array_int2 =  Array {
    typoid      = Oid 1005,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_int2",
    typelem     = int2
  }

array_int2vector :: TypeInfo
array_int2vector =  Array {
    typoid      = Oid 1006,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_int2vector",
    typelem     = int2vector
  }

array_int4 :: TypeInfo
array_int4 =  Array {
    typoid      = Oid 1007,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_int4",
    typelem     = int4
  }

array_regproc :: TypeInfo
array_regproc =  Array {
    typoid      = Oid 1008,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regproc",
    typelem     = regproc
  }

array_text :: TypeInfo
array_text =  Array {
    typoid      = Oid 1009,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_text",
    typelem     = text
  }

array_tid :: TypeInfo
array_tid =  Array {
    typoid      = Oid 1010,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_tid",
    typelem     = tid
  }

array_xid :: TypeInfo
array_xid =  Array {
    typoid      = Oid 1011,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_xid",
    typelem     = xid
  }

array_cid :: TypeInfo
array_cid =  Array {
    typoid      = Oid 1012,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_cid",
    typelem     = cid
  }

array_oidvector :: TypeInfo
array_oidvector =  Array {
    typoid      = Oid 1013,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_oidvector",
    typelem     = oidvector
  }

array_bpchar :: TypeInfo
array_bpchar =  Array {
    typoid      = Oid 1014,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_bpchar",
    typelem     = bpchar
  }

array_varchar :: TypeInfo
array_varchar =  Array {
    typoid      = Oid 1015,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_varchar",
    typelem     = varchar
  }

array_int8 :: TypeInfo
array_int8 =  Array {
    typoid      = Oid 1016,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_int8",
    typelem     = int8
  }

array_point :: TypeInfo
array_point =  Array {
    typoid      = Oid 1017,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_point",
    typelem     = point
  }

array_lseg :: TypeInfo
array_lseg =  Array {
    typoid      = Oid 1018,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_lseg",
    typelem     = lseg
  }

array_path :: TypeInfo
array_path =  Array {
    typoid      = Oid 1019,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_path",
    typelem     = path
  }

array_box :: TypeInfo
array_box =  Array {
    typoid      = Oid 1020,
    typcategory = 'A',
    typdelim    = ';',
    typname     = "_box",
    typelem     = box
  }

array_float4 :: TypeInfo
array_float4 =  Array {
    typoid      = Oid 1021,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_float4",
    typelem     = float4
  }

array_float8 :: TypeInfo
array_float8 =  Array {
    typoid      = Oid 1022,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_float8",
    typelem     = float8
  }

array_abstime :: TypeInfo
array_abstime =  Array {
    typoid      = Oid 1023,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_abstime",
    typelem     = abstime
  }

array_reltime :: TypeInfo
array_reltime =  Array {
    typoid      = Oid 1024,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_reltime",
    typelem     = reltime
  }

array_tinterval :: TypeInfo
array_tinterval =  Array {
    typoid      = Oid 1025,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_tinterval",
    typelem     = tinterval
  }

array_polygon :: TypeInfo
array_polygon =  Array {
    typoid      = Oid 1027,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_polygon",
    typelem     = polygon
  }

array_oid :: TypeInfo
array_oid =  Array {
    typoid      = Oid 1028,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_oid",
    typelem     = oid
  }

array_aclitem :: TypeInfo
array_aclitem =  Array {
    typoid      = Oid 1034,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_aclitem",
    typelem     = aclitem
  }

array_macaddr :: TypeInfo
array_macaddr =  Array {
    typoid      = Oid 1040,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_macaddr",
    typelem     = macaddr
  }

array_inet :: TypeInfo
array_inet =  Array {
    typoid      = Oid 1041,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_inet",
    typelem     = inet
  }

array_timestamp :: TypeInfo
array_timestamp =  Array {
    typoid      = Oid 1115,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_timestamp",
    typelem     = timestamp
  }

array_date :: TypeInfo
array_date =  Array {
    typoid      = Oid 1182,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_date",
    typelem     = date
  }

array_time :: TypeInfo
array_time =  Array {
    typoid      = Oid 1183,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_time",
    typelem     = time
  }

array_timestamptz :: TypeInfo
array_timestamptz =  Array {
    typoid      = Oid 1185,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_timestamptz",
    typelem     = timestamptz
  }

array_interval :: TypeInfo
array_interval =  Array {
    typoid      = Oid 1187,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_interval",
    typelem     = interval
  }

array_numeric :: TypeInfo
array_numeric =  Array {
    typoid      = Oid 1231,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_numeric",
    typelem     = numeric
  }

array_cstring :: TypeInfo
array_cstring =  Array {
    typoid      = Oid 1263,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_cstring",
    typelem     = cstring
  }

array_timetz :: TypeInfo
array_timetz =  Array {
    typoid      = Oid 1270,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_timetz",
    typelem     = timetz
  }

array_bit :: TypeInfo
array_bit =  Array {
    typoid      = Oid 1561,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_bit",
    typelem     = bit
  }

array_varbit :: TypeInfo
array_varbit =  Array {
    typoid      = Oid 1563,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_varbit",
    typelem     = varbit
  }

array_refcursor :: TypeInfo
array_refcursor =  Array {
    typoid      = Oid 2201,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_refcursor",
    typelem     = refcursor
  }

array_regprocedure :: TypeInfo
array_regprocedure =  Array {
    typoid      = Oid 2207,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regprocedure",
    typelem     = regprocedure
  }

array_regoper :: TypeInfo
array_regoper =  Array {
    typoid      = Oid 2208,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regoper",
    typelem     = regoper
  }

array_regoperator :: TypeInfo
array_regoperator =  Array {
    typoid      = Oid 2209,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regoperator",
    typelem     = regoperator
  }

array_regclass :: TypeInfo
array_regclass =  Array {
    typoid      = Oid 2210,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regclass",
    typelem     = regclass
  }

array_regtype :: TypeInfo
array_regtype =  Array {
    typoid      = Oid 2211,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regtype",
    typelem     = regtype
  }

array_record :: TypeInfo
array_record =  Array {
    typoid      = Oid 2287,
    typcategory = 'P',
    typdelim    = ',',
    typname     = "_record",
    typelem     = record
  }

array_txid_snapshot :: TypeInfo
array_txid_snapshot =  Array {
    typoid      = Oid 2949,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_txid_snapshot",
    typelem     = txid_snapshot
  }

array_uuid :: TypeInfo
array_uuid =  Array {
    typoid      = Oid 2951,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_uuid",
    typelem     = uuid
  }

array_pg_lsn :: TypeInfo
array_pg_lsn =  Array {
    typoid      = Oid 3221,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_pg_lsn",
    typelem     = pg_lsn
  }

array_tsvector :: TypeInfo
array_tsvector =  Array {
    typoid      = Oid 3643,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_tsvector",
    typelem     = tsvector
  }

array_gtsvector :: TypeInfo
array_gtsvector =  Array {
    typoid      = Oid 3644,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_gtsvector",
    typelem     = gtsvector
  }

array_tsquery :: TypeInfo
array_tsquery =  Array {
    typoid      = Oid 3645,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_tsquery",
    typelem     = tsquery
  }

array_regconfig :: TypeInfo
array_regconfig =  Array {
    typoid      = Oid 3735,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regconfig",
    typelem     = regconfig
  }

array_regdictionary :: TypeInfo
array_regdictionary =  Array {
    typoid      = Oid 3770,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regdictionary",
    typelem     = regdictionary
  }

array_jsonb :: TypeInfo
array_jsonb =  Array {
    typoid      = Oid 3807,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_jsonb",
    typelem     = jsonb
  }

array_int4range :: TypeInfo
array_int4range =  Array {
    typoid      = Oid 3905,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_int4range",
    typelem     = int4range
  }

array_numrange :: TypeInfo
array_numrange =  Array {
    typoid      = Oid 3907,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_numrange",
    typelem     = numrange
  }

array_tsrange :: TypeInfo
array_tsrange =  Array {
    typoid      = Oid 3909,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_tsrange",
    typelem     = tsrange
  }

array_tstzrange :: TypeInfo
array_tstzrange =  Array {
    typoid      = Oid 3911,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_tstzrange",
    typelem     = tstzrange
  }

array_daterange :: TypeInfo
array_daterange =  Array {
    typoid      = Oid 3913,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_daterange",
    typelem     = daterange
  }

array_int8range :: TypeInfo
array_int8range =  Array {
    typoid      = Oid 3927,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_int8range",
    typelem     = int8range
  }

array_regnamespace :: TypeInfo
array_regnamespace =  Array {
    typoid      = Oid 4090,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regnamespace",
    typelem     = regnamespace
  }

array_regrole :: TypeInfo
array_regrole =  Array {
    typoid      = Oid 4097,
    typcategory = 'A',
    typdelim    = ',',
    typname     = "_regrole",
    typelem     = regrole
  }
